### PR TITLE
fix missing text for notificationcenter

### LINKED ISSUE #12: Benachrichtigungstyp für Lagerbestandsmails wird im Notification Center nicht angezeigt
Hallo,
im Notification Center fehlt in der Liste der Name des Benachrichtigungstyps:

grafik

Steffen

### PR DESCRIPTION
**Pull request by sgei**
Fix for missing text for notification type:
Closes #12

grafik

### CODE REVIEW

**Comment by richardhj** [comment]
Closes #12.

**Comment by richardhj** [comment]
Hi @sgei
if you want to see the changes in this repository, you might want to batch and commit or comment on the changes I proposed.

**Comment by sgei** [comment]
Hi @richardhj,
what should I do now?

**Review by sgei — COMMENTED** [review]
#14 adding these xlf-files will fix the issue

**Review by sgei — COMMENTED** [review]
Okay, now I see your changes...
I've tested these changes and it's working fine.

**Pull request merged**
